name: chatwithdocs
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get: 4.6.6
  googleai_dart: ^0.0.2+2
  langchain: ^0.4.1
  langchain_google: ^0.2.3+3
  langchain_openai: ^0.4.0+1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^24.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
